name: Build for linux
on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Linux Flutter builder
    runs-on: ubuntu-latest
    env:
      appVersion: 1.0.0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.0.1

      - run: |
          flutter clean
          flutter pub get
          flutter config --enable-linux-desktop
          flutter build linux --release

      - uses: actions/upload-artifact@v3
        with:
          name: release-linux
          path: build/app/outputs/
